import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {spawn} from 'node:child_process';
import {DatabaseSync} from 'node:sqlite';
import {randomBytes,scryptSync} from 'node:crypto';
const dir=mkdtempSync(join(tmpdir(),'rejvi-test-')),origin='http://localhost:3187';
let child,cookie='',csrf='';
async function req(path,method='GET',data,auth=true,extra={}){const r=await fetch(origin+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...(auth?{Cookie:cookie,'X-CSRF-Token':csrf}:{}),...extra},...(data!==undefined?{body:JSON.stringify(data)}:{})});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')};}
test('portfolio security, content, inbox, upload and persistence',async()=>{try{
 child=spawn(process.execPath,['server.mjs'],{cwd:resolve('.'),env:{...process.env,DATA_DIR:dir,PORT:'3187',APP_ORIGIN:origin},stdio:'pipe'});
 await new Promise((resolve,reject)=>{child.stdout.once('data',resolve);child.once('error',reject);child.once('exit',()=>reject(Error('Server exited early')));});
 const db=new DatabaseSync(join(dir,'portfolio.sqlite')),salt=randomBytes(24).toString('hex');db.prepare('INSERT INTO admin VALUES(1,?,?,?)').run('owner@example.com',salt,scryptSync('test-password-12345',salt,64).toString('hex'));db.close();
 assert.equal((await req('/api/admin/content')).status,401);
 assert.equal((await req('/api/login','POST',{email:'owner@example.com',password:'wrong'},false)).status,401);
 const login=await req('/api/login','POST',{email:'owner@example.com',password:'test-password-12345'},false);assert.equal(login.status,200);cookie=login.cookie.split(';')[0];csrf=login.body.csrf;assert.match(login.cookie,/HttpOnly/);
 const original=(await req('/api/admin/content')).body;assert.equal(original.projects.length,3);
 assert.equal((await req('/api/admin/content','PUT',original,true,{'X-CSRF-Token':'bad'})).status,403);
 assert.equal((await req('/api/admin/content','PUT',original,true,{Origin:'https://evil.example'})).status,403);
 const edited=structuredClone(original);edited.profile.name='Saved Test';edited.projects[0].published=false;
 const saved=await req('/api/admin/content','PUT',edited);assert.equal(saved.status,200,JSON.stringify(saved.body));edited._revision=saved.body.revision;assert.equal((await req('/api/admin/content','PUT',original)).status,409);
 const pub=(await req('/api/content')).body;assert.equal(pub.profile.name,'Saved Test');assert.equal(pub.projects.length,2);
 edited.profile.github='javascript:alert(1)';assert.equal((await req('/api/admin/content','PUT',edited)).status,400);
 assert.equal((await req('/api/contact','POST',{name:'Visitor',email:'visitor@example.com',message:'A valid test conversation.'},false)).status,201);
 const messages=(await req('/api/admin/messages')).body;assert.equal(messages.length,1);
 assert.equal((await req('/api/admin/messages/'+messages[0].id,'PATCH',{status:'read'})).status,200);
 assert.equal((await req('/api/admin/messages')).body[0].status,'read');
 assert.equal((await req('/api/admin/upload','POST',{data:Buffer.from('<svg>bad content</svg>').toString('base64')})).status,400);
 const upload=await req('/api/admin/upload','POST',{data:Buffer.from('%PDF-1.4\ntest document').toString('base64')});assert.equal(upload.status,201);assert.equal((await fetch(origin+upload.body.url)).status,200);
 const media=(await req('/api/admin/media')).body;assert.equal(media.length,1);assert.equal(media[0].inUse,false);
 const mediaName=upload.body.url.split('/').pop();assert.equal((await req('/api/admin/media/'+mediaName,'DELETE',{force:false})).status,200);assert.equal((await fetch(origin+upload.body.url)).status,404);
 assert.equal((await fetch(origin+'/data/portfolio.sqlite')).status,404);
 assert.equal((await req('/api/admin/export')).body.messages.length,1);
 const checkDb=new DatabaseSync(join(dir,'portfolio.sqlite'));assert.equal(JSON.parse(checkDb.prepare('SELECT json FROM content').get().json).profile.name,'Saved Test');checkDb.close();
 // Publishing lifecycle: drafts are private, comments are moderated, emails never public.
 const draft={title:'Test article',slug:'test-article',excerpt:'A test article',body:'# Hello\nA useful article with **details**.',category:'Engineering',tags:'Node, SQLite',cover:'',status:'draft',comments:true};
 const created=await req('/api/admin/articles','POST',draft);assert.equal(created.status,201,JSON.stringify(created.body));
 assert.equal((await req('/api/articles/test-article')).status,404);
 assert.equal((await fetch(origin+'/articles/test-article')).status,404);
 const published=await req('/api/admin/articles/'+created.body.id,'PUT',{...created.body,status:'published'});assert.equal(published.status,200);
 assert.equal((await req('/api/articles')).body.length,1);assert.equal((await fetch(origin+'/articles/test-article')).status,200);
 const cmt=await req('/api/articles/test-article/comments','POST',{name:'Reader',email:'private@example.com',body:'A useful comment.'},false);assert.equal(cmt.status,201);
 assert.equal((await req('/api/articles/test-article/comments')).body.length,0);
 const comments=(await req('/api/admin/comments')).body;assert.equal(comments[0].email,'private@example.com');
 assert.equal((await req('/api/admin/comments/'+comments[0].id,'PATCH',{status:'approved',reply:'Thank you for reading.'})).status,200);
 const pubComments=(await req('/api/articles/test-article/comments')).body;assert.equal(pubComments[0].reply,'Thank you for reading.');assert.equal('email' in pubComments[0],false);
 const react=await req('/api/articles/test-article/reactions','POST',{kind:'like'},false);assert.equal(react.status,200);const reader=react.cookie.split(';')[0];
 const again=await req('/api/articles/test-article/reactions','POST',{kind:'love'},false,{Cookie:reader});assert.equal(again.body.reactions.love,1);assert.equal(again.body.reactions.like,undefined);
 const remove=await req('/api/articles/test-article/reactions','POST',{kind:null},false,{Cookie:reader});assert.deepEqual(remove.body.reactions,{});
 assert.equal((await req('/api/admin/articles/'+created.body.id,'PUT',{...created.body,status:'published'})).status,409);
 assert.equal((await req('/api/admin/history')).body.length,1);
 for(const route of ['/about','/work','/resume','/articles','/contact','/privacy'])assert.equal((await fetch(origin+route)).status,200,route);
 const finalContent=(await req('/api/admin/content')).body;finalContent.pages.push({id:'lab',slug:'lab',label:'Lab',title:'My lab',subtitle:'Experiments',body:'Hello lab',image:'',visible:true});
 assert.equal((await req('/api/admin/content','PUT',finalContent)).status,200);assert.equal((await fetch(origin+'/lab')).status,200);
 const hide=(await req('/api/admin/content')).body;hide.pages.find(x=>x.id==='articles').visible=false;assert.equal((await req('/api/admin/content','PUT',hide)).status,200);assert.equal((await req('/api/articles')).status,404);assert.equal((await fetch(origin+'/articles/test-article')).status,404);
 assert.equal((await req('/api/admin/articles/'+created.body.id,'DELETE',{})).status,200);assert.equal((await req('/api/admin/comments')).body.length,0);
 assert.equal((await req('/api/admin/password','PUT',{current:'test-password-12345',password:'replacement-password-123'})).status,200);assert.equal((await req('/api/admin/session')).status,401);
 console.log('Verified articles, moderation, email privacy, reactions, multipage routing, hidden pages, revision conflicts, history and authentication, CSRF, origin checks, draft filtering, persistence, URL validation, contact inbox, upload filtering, export, and session revocation.');
 }finally{child?.kill();await new Promise(r=>child?.once('exit',r));rmSync(dir,{recursive:true,force:true});}});
